parameters:
#    julian_cand_test.example.class: Julian\Bundle\CandTestBundle\Example

services:
#    julian_cand_test.example:
#        class: %julian_cand_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
