security:
    encoders:
        Wedding\AdminBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: WeddingAdminBundle:User }

    firewalls:
        admin_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/admin$, roles: ROLE_ADMIN }
        - { path: ^/admin/adduser/, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/adduser$, roles: ROLE_SUPER_ADMIN }

