<?php

namespace Fishrod\WeddingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WeddingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeddingRepository extends EntityRepository
{
    public function getLatestWeddings($maxResults = 20)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb
            ->select('w, g')
            ->from('FishrodWeddingBundle:Wedding', 'w')
            ->leftJoin('w.guests', 'g')
            ->orderBy('w.id', 'DESC')
            ->setMaxResults($maxResults)
            ->getQuery()->getArrayResult();
    }
}
