<?php

namespace Fishrod\WeddingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WeddingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeddingRepository extends EntityRepository
{
}
